name: bmkg_client
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies: 
  dio: '>=4.0.0 <5.0.0' 
  equatable: '>=2.0.0 <3.0.0' 
  xml: '>=6.0.0 <7.0.0' 
